spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

logging.level.liquibase=DEBUG
logging.level.org.springframework.jdbc=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/classified
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:8642}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=YourVeryLong256BitSecretKeyValueForHS256Algorithm!!!
jwt.expirationMs=3600000